os: linux
dist: focal
language: ruby
services:
  - mysql
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
rvm:
  - 2.6
  - 2.7
  - 3.0
jobs:
  exclude:
    - rvm: 3.0
      gemfile: gemfiles/rails_5.2.gemfile
before_install:
  - "[[ $BUNDLE_GEMFILE =~ rails_4\\.2 ]] && gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true"
  - "[[ $BUNDLE_GEMFILE =~ rails_4\\.2 ]] && gem install bundler -v '< 2' || true"
